Commit

diff --git a/.github/workflows/change-api-url.yml b/.github/workflows/change-api-url.yml
--- a/.github/workflows/change-api-url.yml
+++ b/.github/workflows/change-api-url.yml
@@ -159,19 +159,43 @@ jobs:
       #     echo "Extracted Deployment URL: $DEPLOYMENT_URL"
       #     echo "static_web_app_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
 
+      - name: Get Preview Environment URL
+        id: get-preview-url
+        run: |
+          echo "Logging in to Azure..."
+          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} --output none
+
+          echo "Fetching preview environment URL..."
+          STATIC_WEB_APP_NAME="${{ vars.AZURE_STATIC_WEB_APP_NAME }}"
+          ENVIRONMENT_NAME="dev"
+
+          # Pobierz URL środowiska `dev`
+          PREVIEW_URL=$(az staticwebapp environment list \
+            --name $STATIC_WEB_APP_NAME \
+            --query "[?name=='$ENVIRONMENT_NAME'].hostname" \
+            -o tsv)
+
+          if [ -z "$PREVIEW_URL" ]; then
+            echo "❌ ERROR: Preview environment URL not found for environment '$ENVIRONMENT_NAME'"
+            exit 1
+          fi
+
+          echo "Preview Environment URL: $PREVIEW_URL"
+          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT'
+
       - name: Comment on PR
         uses: actions/github-script@v6
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            #const staticWebAppUrl = `${{ steps.extract-url.outputs.static_web_app_url }}`;
+            const staticWebAppUrl = `${{ steps.get-preview-url.outputs.preview_url }}`;
             const apiUrl = `${{ needs.process-comment.outputs.api_url }}`;
-            #- **Frontend URL**: [${staticWebAppUrl}](${staticWebAppUrl})
+
             const commentBody = `
             ### Rebuild and Deployment Complete
             The application has been rebuilt and deployed with the following details:
             
-            
+            - **Frontend URL**: [http://${staticWebAppUrl}](http://${staticWebAppUrl})
             - **API URL**: [${apiUrl}](${apiUrl})
             `;
             
