Commit

diff --git a/.github/workflows/pull-request-environment.yml b/.github/workflows/pull-request-environment.yml
--- a/.github/workflows/pull-request-environment.yml
+++ b/.github/workflows/pull-request-environment.yml
@@ -147,8 +147,18 @@ jobs:
       - name: Extract Deployment URL
         id: extract-url
         run: |
+          # Zapisz logi do pliku
+          LOG_FILE=$(mktemp)
+          echo "Extracting deployment URL from logs..."
+          cat $GITHUB_STEP_SUMMARY > $LOG_FILE
+
           # Wyodrębnij URL z logów
-          DEPLOYMENT_URL=$(cat $GITHUB_ENV | grep "Visit your site at:" | awk '{print $5}')
+          DEPLOYMENT_URL=$(grep -oP 'Visit your site at: \K(https?://\S+)' $LOG_FILE)
+          if [ -z "$DEPLOYMENT_URL" ]; then
+            echo "❌ ERROR: Deployment URL not found in logs!"
+            exit 1
+          fi
+
           echo "Extracted Deployment URL: $DEPLOYMENT_URL"
           echo "static_web_app_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
 
@@ -207,3 +217,4 @@ jobs:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_PRODUCTION_WEBAPP_TOKEN }}
           action: "close"
           deployment_environment: dev
+          pull_request_id: ${{ steps.extract-pr-number.outputs.pr_number }}
